---
development:
  cloud_name: colin-techmaster-rails
  api_key: '628544996988455'
  api_secret: UUtcni-jDGtPfXJMHymQvOeAffY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: colin-techmaster-rails
  api_key: '628544996988455'
  api_secret: UUtcni-jDGtPfXJMHymQvOeAffY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: colin-techmaster-rails
  api_key: '628544996988455'
  api_secret: UUtcni-jDGtPfXJMHymQvOeAffY
  enhance_image_tag: true
  static_image_support: false
