# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5853f42583d60851061ced5f26360cf6d0be69cac95d43497cb0c6cb562b8bbe0c4fb54dcd175c032cb50e57562bd9aa5271be9fa85952a4ea062e564961a67

test:
  secret_key_base: e72b0f34fbf236519040ef547821e48ef64a6b78baa185af02987fbc23f3ea714556ea65c843db7963c5afcd55ef647fab092af83c36ffdf2c33ccbaaf6b0e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
